export enum EntityEnum {
    USER = 'users',
    TASK = 'tasks',
    SONG = 'songs',
    MINISTER = 'ministers',
    MINISTER_SONG_KEY = 'minister_song_keys',
    CHURCH = 'churches',
    EXTRA_EVENT = 'extra_events',
    SECTOR = 'sectors',
    UNAVAILABILITY = 'unavailability',
    SCALE = 'scales',
    SCALE_SONG = 'scale_songs',
    USER_TASK = 'users_tasks',
    PARTICIPANTS = 'participants',
    USER_CHURCH = 'user_church',
    VERIFICATION_CODE = 'verification_codes',
    PASSWORD_RESET_TOKEN = 'password_reset_tokens',
    USER_SECTOR = 'user_sectors',
}
